# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0003_auto_20171111_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='edge',
            name='next_node_id',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='history',
            name='hist_id',
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='edge',
            name='current_state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='chatBot.State'),
        ),
        migrations.AddField(
            model_name='edge',
            name='next_state_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='chatBot.State'),
        ),
    ]
