# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0004_auto_20171121_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
