# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0005_auto_20171121_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='edge_id',
        ),
        migrations.AddField(
            model_name='response',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatBot.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='book_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
