# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0007_auto_20171223_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='recommended_response',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
